version: '3'
services:
  app:
    image: alpine
    volumes:
      - ./app/php:/app/app/php
      - ./app/mysql:/app/app/mysql
    command: sh -c "apk add --no-cache git && \
                    mkdir -p /app/app/php && \
                    git clone https://github.com/bcit-ci/CodeIgniter.git /app/app/php && \
                    echo 'FROM php:7.4-apache' > /app/app/php/Dockerfile && \
                    echo 'RUN apt-get update && apt-get upgrade -y && apt-get install -y nano' >> /app/app/php/Dockerfile && \
                    echo 'RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli \\' >> /app/app/php/Dockerfile && \
                    echo '  && a2enmod headers \\' >> /app/app/php/Dockerfile && \
                    echo '  && sed -ri -e \"s/^([ \t]*)(<\\/VirtualHost>)/\\1\\tHeader set Access-Control-Allow-Origin \\\"*\\\"\\n\\1\\2/g\" /etc/apache2/sites-available/*.conf' >> /app/app/php/Dockerfile && \
                    echo 'ENV TERM xterm' >> /app/app/php/Dockerfile && \
                    echo 'EXPOSE 80' >> /app/app/php/Dockerfile && \
                    mkdir -p /app/app/mysql && \
                    echo 'FROM mysql' > /app/app/mysql/Dockerfile && \
                    echo 'COPY ./db_dump.sql /docker-entrypoint-initdb.d/' >> /app/app/mysql/Dockerfile && \
                    echo \"CREATE DATABASE IF NOT EXISTS \\\`${DB_NAME}\\\`;\" > /app/app/mysql/db_dump.sql && \
                    echo \"USE \\\`${DB_NAME}\\\`;\" >> /app/app/mysql/db_dump.sql && \
                    echo \"DROP TABLE IF EXISTS \\\`Users\\\`;\" >> /app/app/mysql/db_dump.sql && \
                    echo \"CREATE TABLE \\\`Users\\\` (\" >> /app/app/mysql/db_dump.sql && \
                    echo \"  \\\`id\\\` int(11) NOT NULL AUTO_INCREMENT,\" >> /app/app/mysql/db_dump.sql && \
                    echo \"  \\\`name\\\` varchar(250) NOT NULL,\" >> /app/app/mysql/db_dump.sql && \
                    echo \"  \\\`email\\\` varchar(250) NOT NULL,\" >> /app/app/mysql/db_dump.sql && \
                    echo \"  PRIMARY KEY (\\\`id\\\`),\" >> /app/app/mysql/db_dump.sql && \
                    echo \"  UNIQUE KEY \\\`email_UNIQUE\\\` (\\\`email\\\`)\" >> /app/app/mysql/db_dump.sql && \
                    echo \") ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\" >> /app/app/mysql/db_dump.sql && \
                    echo \"LOCK TABLES \\\`Users\\\` WRITE;\" >> /app/app/mysql/db_dump.sql && \
                    echo \"INSERT INTO \\\`Users\\\` VALUES (1,'nico','ncr2345@gmail.com');\" >> /app/app/mysql/db_dump.sql && \
                    echo \"UNLOCK TABLES;\" >> /app/app/mysql/db_dump.sql"
